name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # जब भी main ब्रांच में कोड आए, काम शुरू हो जाए

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }} # गूगल क्लाउड की गुप्त चाबी

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: sbrbioforge
        region: us-central1
